import {ALL_CHECKPOINTS, type CheckpointLocation} from '../data/tulsa-map';

export type CourseStyle =
  | 'Around Gradient'
  | 'More rooftop jumps'
  | 'Beginner friendly'
  | 'Maximum chaos';

export interface CoursePlan {
  id: string;
  name: string;
  style: CourseStyle;
  checkpointIds: string[];
  isGeminiGenerated: boolean;
  generatedAt?: string;
  description: string;
}

export class CourseDirector {
  private presetCourses: Record<CourseStyle, CoursePlan> = {
    'Around Gradient': {
      id: 'course-around-gradient',
      name: 'Around Gradient Landmark',
      style: 'Around Gradient',
      checkpointIds: [
        'cp-gradient-street',
        'cp-gradient-beacon',
        'cp-center-universe',
        'cp-tulsa-theater',
        'cp-gradient-street',
      ],
      isGeminiGenerated: false,
      description:
        'Classic downtown loop encircling 12 N Cheyenne Ave Gradient landmark.',
    },
    'More rooftop jumps': {
      id: 'course-rooftop-jumps',
      name: 'Rooftop Rampage',
      style: 'More rooftop jumps',
      checkpointIds: [
        'cp-gradient-street',
        'cp-gradient-beacon',
        'cp-tulsa-theater',
        'cp-union-station',
        'cp-bok-center',
      ],
      isGeminiGenerated: false,
      description:
        'High-elevation stunt course jumping low-rise downtown roofs.',
    },
    'Beginner friendly': {
      id: 'course-beginner',
      name: 'Street Level Cruise',
      style: 'Beginner friendly',
      checkpointIds: [
        'cp-gradient-street',
        'cp-center-universe',
        'cp-guthrie-green',
        'cp-bok-tower-plaza',
        'cp-gradient-street',
      ],
      isGeminiGenerated: false,
      description: 'Wide street-level track avoiding steep rooftop jumps.',
    },
    'Maximum chaos': {
      id: 'course-chaos',
      name: 'Tulsa Skyline Chaos',
      style: 'Maximum chaos',
      checkpointIds: [
        'cp-gradient-boost-gap',
        'cp-gradient-beacon',
        'cp-bok-center',
        'cp-union-station',
        'cp-tulsa-theater',
        'cp-gradient-boost-gap',
      ],
      isGeminiGenerated: false,
      description:
        'Maximum height jumps and skyway gaps requiring boost timing.',
    },
  };

  public getPresetCourse(style: CourseStyle): CoursePlan {
    return this.presetCourses[style] || this.presetCourses['Around Gradient'];
  }

  public resolveCheckpoints(course: CoursePlan): CheckpointLocation[] {
    const map = new Map(ALL_CHECKPOINTS.map(cp => [cp.id, cp]));
    const resolved: CheckpointLocation[] = [];

    for (const id of course.checkpointIds) {
      const cp = map.get(id);
      if (cp) {
        resolved.push(cp);
      }
    }

    return resolved.length > 0 ? resolved : ALL_CHECKPOINTS.slice(0, 5);
  }

  public async generateAICourse(
    style: CourseStyle,
    apiKey?: string,
  ): Promise<CoursePlan> {
    const presetFallback = this.getPresetCourse(style);

    if (!apiKey) {
      return presetFallback;
    }

    try {
      const prompt = `Generate a 5-checkpoint stunt race course in downtown Tulsa for style "${style}". Choose 5 IDs from: ${ALL_CHECKPOINTS.map(c => c.id).join(', ')}. Return JSON with format {"name": string, "checkpointIds": string[], "description": string}.`;

      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
        {
          method: 'POST',
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify({
            contents: [{parts: [{text: prompt}]}],
            generationConfig: {
              responseMimeType: 'application/json',
            },
          }),
        },
      );

      if (!response.ok) {
        return presetFallback;
      }

      const data = await response.json();
      const jsonText = data.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!jsonText) return presetFallback;

      const parsed = JSON.parse(jsonText) as {
        name?: string;
        checkpointIds?: string[];
        description?: string;
      };

      if (
        !Array.isArray(parsed.checkpointIds) ||
        parsed.checkpointIds.length === 0
      ) {
        return presetFallback;
      }

      // Validate all returned IDs exist in allowlist
      const validIds = parsed.checkpointIds.filter(id =>
        ALL_CHECKPOINTS.some(cp => cp.id === id),
      );

      if (validIds.length < 3) return presetFallback;

      return {
        id: `gemini-course-${Date.now()}`,
        name: parsed.name || `Gemini ${style}`,
        style,
        checkpointIds: validIds,
        isGeminiGenerated: true,
        generatedAt: new Date().toISOString(),
        description:
          parsed.description || 'Custom course generated by Gemini AI.',
      };
    } catch {
      return presetFallback;
    }
  }
}
